import type { Metadata } from "next";
import 'bootstrap/dist/css/bootstrap.min.css'
import "./globals.css";
import PortfolioNav from "./components/PortfolioNav";

export const metadata: Metadata = {
  title: "Sethu | Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <PortfolioNav/>
        {children}
      </body>
    </html>
  );
}
